# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -Djar.finalName=my-testing-framework -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
