# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{github.event.pull_request.head.ref}}

    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Increment build number
      run: |
        mvn build-helper:parse-version versions:set "-DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}" versions:commit
        git add ./pom.xml
        git -c "user.name=Github Actions" -c "user.email=${{ secrets.EMAIL }}" commit -m "Increment build number"
        git push

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Build Maven project
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging

    - name: Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-testing-framework
        path: staging
